# Puerto del Servicio de Logística
server.port=8083

# Configuración de la Base de Datos (ejemplo con MySQL, cambialo si usan Postgres)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/donatrack?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
